[tool.poetry]
name = "poetry-instance"
version = "1.5.1"
description = ""
authors = []
license = ""

[tool.poetry.dependencies]
python = "3.10.6"
poetry = {version = "^1.5.1", allow-prereleases = true}
